// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEKj47Ht9oJO_G5MjBGdrzLw-Wpt02pls',
    appId: '1:806815649378:web:300e48570f55d325ea0b3b',
    messagingSenderId: '806815649378',
    projectId: 'flutter-tutor-app-e8851',
    authDomain: 'flutter-tutor-app-e8851.firebaseapp.com',
    storageBucket: 'flutter-tutor-app-e8851.firebasestorage.app',
    measurementId: 'G-0H5DWEMFHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6zIBBCiR57oiTNDgM0IS7RK7ut5pakJ4',
    appId: '1:806815649378:android:4f2e129267cec80dea0b3b',
    messagingSenderId: '806815649378',
    projectId: 'flutter-tutor-app-e8851',
    storageBucket: 'flutter-tutor-app-e8851.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZM_OUQx3649OdzjS70Rnvu3j6D7Jyuyo',
    appId: '1:806815649378:ios:1d46b816ca12acb7ea0b3b',
    messagingSenderId: '806815649378',
    projectId: 'flutter-tutor-app-e8851',
    storageBucket: 'flutter-tutor-app-e8851.firebasestorage.app',
    iosBundleId: 'com.example.courseClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZM_OUQx3649OdzjS70Rnvu3j6D7Jyuyo',
    appId: '1:806815649378:ios:1d46b816ca12acb7ea0b3b',
    messagingSenderId: '806815649378',
    projectId: 'flutter-tutor-app-e8851',
    storageBucket: 'flutter-tutor-app-e8851.firebasestorage.app',
    iosBundleId: 'com.example.courseClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEKj47Ht9oJO_G5MjBGdrzLw-Wpt02pls',
    appId: '1:806815649378:web:d2955993e4cce41eea0b3b',
    messagingSenderId: '806815649378',
    projectId: 'flutter-tutor-app-e8851',
    authDomain: 'flutter-tutor-app-e8851.firebaseapp.com',
    storageBucket: 'flutter-tutor-app-e8851.firebasestorage.app',
    measurementId: 'G-MF609BPMTX',
  );
