// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNe75KPZRpkoQDKI1daB1PEsUFragc9-E',
    appId: '1:133997409673:ios:60d79bb14a4ec656bb5d58',
    messagingSenderId: '133997409673',
    projectId: 'challenge1-25225',
    storageBucket: 'challenge1-25225.firebasestorage.app',
    iosBundleId: 'com.example.courseClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiif0DgqhzejoKVW_0wXkGC39InnfS9Js',
    appId: '1:133997409673:web:4a2c8f21034fece0bb5d58',
    messagingSenderId: '133997409673',
    projectId: 'challenge1-25225',
    authDomain: 'challenge1-25225.firebaseapp.com',
    storageBucket: 'challenge1-25225.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiif0DgqhzejoKVW_0wXkGC39InnfS9Js',
    appId: '1:133997409673:web:391ad8fca4e60928bb5d58',
    messagingSenderId: '133997409673',
    projectId: 'challenge1-25225',
    authDomain: 'challenge1-25225.firebaseapp.com',
    storageBucket: 'challenge1-25225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNe75KPZRpkoQDKI1daB1PEsUFragc9-E',
    appId: '1:133997409673:ios:60d79bb14a4ec656bb5d58',
    messagingSenderId: '133997409673',
    projectId: 'challenge1-25225',
    storageBucket: 'challenge1-25225.firebasestorage.app',
    iosBundleId: 'com.example.courseClone',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9lenwXXwxiuAuOo874Rmg_F2xbosCEgU',
    appId: '1:133997409673:android:379c91ed4ea3c3b1bb5d58',
    messagingSenderId: '133997409673',
    projectId: 'challenge1-25225',
    storageBucket: 'challenge1-25225.firebasestorage.app',
  );

}