// lib/utils/data.dart

import 'package:course_clone/models/course_model.dart';
import 'package:course_clone/models/progress_model.dart';

/// User profile data
final Map<String, String> profile = {
  'name': 'Jeno',
  'image': 'https://avatars.githubusercontent.com/u/86506519?v=4',
  'email': 'sangvaleap.vanny@gmail.com',
};

/// Categories for the home screen
final List<Map<String, String>> categories = [
  {'name': 'All', 'icon': 'assets/icons/category/all.svg'},
  {'name': 'Coding', 'icon': 'assets/icons/category/coding.svg'},
  {'name': 'Education', 'icon': 'assets/icons/category/education.svg'},
  {'name': 'Design', 'icon': 'assets/icons/category/design.svg'},
  {'name': 'Business', 'icon': 'assets/icons/category/business.svg'},
  {'name': 'Cooking', 'icon': 'assets/icons/category/cooking.svg'},
  {'name': 'Music', 'icon': 'assets/icons/category/music.svg'},
  {'name': 'Art', 'icon': 'assets/icons/category/art.svg'},
  {'name': 'Finance', 'icon': 'assets/icons/category/finance.svg'},
];

/// Stub lists for your Course widgets (populate as needed)
final List<Course> courses   = [];
final List<Course> features  = [];
final List<Course> recommends = [];

/// Progress tracking topics, each with a list of sections and a record of completed ones.
final List<Map<String, dynamic>> myProgressCourses = [
  {
    'id': 1,
    'name': 'Basics',
    'image': 'https://via.placeholder.com/150',
    'description': 'Fundamental concepts and setup for Flutter development.',
    'sections': <String>[
      'Flutter – Introduction',
      'Flutter – Architecture Application',
      'Android Studio Setup for Flutter Development',
      'Flutter – Setup for Application Development',
      'Flutter Development on Ubuntu',
    ],
    'completedSections': <String>[],
  },
  {
    'id': 2,
    'name': 'Widgets',
    'image': 'https://via.placeholder.com/150',
    'description': 'Deep dive into Flutter\'s widget system.',
    'sections': <String>[
      'Flutter – Widgets',
      'Flutter – Stateful vs Stateless Widgets',
      'MaterialApp class in Flutter',
      'Scaffold class in Flutter',
      'Flutter – AppBar Widget',
      'Flutter – FloatingActionButton',
      'BottomNavigationBar Widget in Flutter',
      'Drawer Widget in Flutter',
      'Container class in Flutter',
      'Flutter – SizedBox Widget',
      'ClipRRect Widget in Flutter',
      'Flutter – RichText Widget',
      'ListView Class in Flutter',
      'Flutter – GridView',
      'Flutter – TextField',
    ],
    'completedSections': <String>[],
  },
  {
    'id': 3,
    'name': 'UI Components',
    'image': 'https://via.placeholder.com/150',
    'description': 'Building and customizing UI components in Flutter.',
    'sections': <String>[
      'Icon Class in Flutter',
      'Expanded Class in Flutter',
      'Flutter – Checkbox Widget',
      'Flutter – Carousel Slider',
      'Flutter – Staggered Grid View',
      'Flutter – Circular & Linear Progress Indicators',
      'Alert Dialog box in Flutter',
      'Flutter – Dialogs',
      'Flutter – Handling videos',
      'Flutter – Expansion Tile Card',
      'Flutter – Tabs',
      'Flutter – Horizontal List',
      'Flutter – Working with Charts',
      'Flutter – Convex Bottombar',
      'Flutter – Slidable',
      'Flutter – Snackbar',
    ],
    'completedSections': <String>[],
  },
  {
    'id': 4,
    'name': 'Design & Animations',
    'image': 'https://via.placeholder.com/150',
    'description': 'Implementing design patterns and animations.',
    'sections': <String>[
      'Customizing Fonts in Flutter',
      'Flutter – Themes',
      'Flutter – Auto size text',
      'Flutter – Skeleton Text',
      'Flutter – Animation in Route Transition',
      'Flutter – Ripple Effect',
      'Flutter – Lazy Loader',
      'Flutter – Radial Hero Animation',
      'Flutter – Hinge Animation',
      'Flutter – Lottie Animation',
      'ProgressIndicator in Flutter',
      'Flutter – Physics Simulation in Animation',
      'Flutter – Using Google fonts',
      'Flutter – Rotate Transition',
      'Flutter – Animated Splash Screen',
      'Flutter – Shimmer',
      'Rive animations in Flutter',
    ],
    'completedSections': <String>[],
  },
  {
    'id': 5,
    'name': 'Forms & Gestures',
    'image': 'https://via.placeholder.com/150',
    'description': 'Handling user input via forms and gestures.',
    'sections': <String>[
      'Form Validation in Flutter',
      'Designing a Form Submission Page in Flutter',
      'Flutter – Gestures',
    ],
    'completedSections': <String>[],
  },
  {
    'id': 6,
    'name': 'Navigation & Routing',
    'image': 'https://via.placeholder.com/150',
    'description': 'Managing app navigation and routing.',
    'sections': <String>[
      'Routes and Navigator in Flutter',
      'Multi-Page Applications in Flutter',
      'Flutter – Named Routes',
      'Flutter – Arguments in Named Routes',
      'Flutter – Return Data from Screen',
      'URLs in Flutter',
      'Retrieve Data From TextFields in Flutter',
      'Flutter – WebSockets',
      'Flutter – Avoiding Jank',
      'Flutter – Updating Data on the Internet',
      'Flutter – Fetching Data From the Internet',
      'Flutter – Deleting Data On The Internet',
      'Flutter – Sending Data To the Internet',
      'Flutter – Send Data to Screen',
      'Flutter – Send Data to the Screen using RouteSettings',
    ],
    'completedSections': <String>[],
  },
  {
    'id': 7,
    'name': 'Accessing Device',
    'image': 'https://via.placeholder.com/150',
    'description': 'Using device features like camera, storage, sensors.',
    'sections': <String>[
      'Gallery Access in Flutter',
      'Camera Access in Flutter',
      'Background local notifications in Flutter',
      'Restrict Landscape Mode in Flutter',
    ],
    'completedSections': <String>[],
  },
  {
    'id': 8,
    'name': 'Advanced Concepts',
    'image': 'https://via.placeholder.com/150',
    'description': 'Exploring advanced Flutter and Dart topics.',
    'sections': <String>[
      'Flutter – Read and Write Data on Firebase',
      'Mail and SMS in Flutter',
      'Making Calls in Flutter',
      'FAB – Speed Dial in Flutter',
      'Flutter – Wakelock',
      'Implementing REST API in Flutter',
      'HTTP GET Response in Flutter',
    ],
    'completedSections': <String>[],
  },
  {
    'id': 9,
    'name': 'App Projects',
    'image': 'https://via.placeholder.com/150',
    'description': 'Building complete Flutter applications.',
    'sections': <String>[
      'Basic Quiz App In Flutter API',
      'A Hello World App Using Flutter',
      'Creating a Simple Application in Flutter',
      'Flutter – Simple PDF-Generating App',
      'Flutter – Dice Roller App',
      'Flutter – Magic 8-Ball App',
    ],
    'completedSections': <String>[],
  },
];


final List<Topic> topics = [
  Topic(
    id: 1,
    name: 'Basics',
    image: 'https://via.placeholder.com/150',
    description: 'Fundamental concepts and setup for Flutter development.',
    sections: [
      'Flutter – Introduction',
      'Flutter – Architecture Application',
      'Android Studio Setup for Flutter Development',
      'Flutter – Setup for Application Development',
      'Flutter Development on Ubuntu',
    ],
  ),
  Topic(
    id: 2,
    name: 'Widgets',
    image: 'https://via.placeholder.com/150',
    description: 'Deep dive into Flutter\'s widget system.',
    sections: [
      'Flutter – Widgets',
      'Flutter – Stateful vs Stateless Widgets',
      'MaterialApp class in Flutter',
      'Scaffold class in Flutter',
      'Flutter – AppBar Widget',
      'Flutter – FloatingActionButton',
      'BottomNavigationBar Widget in Flutter',
      'Drawer Widget in Flutter',
      'Container class in Flutter',
      'Flutter – SizedBox Widget',
      'ClipRRect Widget in Flutter',
      'Flutter – RichText Widget',
      'ListView Class in Flutter',
      'Flutter – GridView',
      'Flutter – TextField',
    ],
  ),
  Topic(
    id: 3,
    name: 'UI Components',
    image: 'https://via.placeholder.com/150',
    description: 'Building and customizing UI components in Flutter.',
    sections: [
      'Icon Class in Flutter',
      'Expanded Class in Flutter',
      'Flutter – Checkbox Widget',
      'Flutter – Carousel Slider',
      'Flutter – Staggered Grid View',
      'Flutter – Circular & Linear Progress Indicators',
      'Alert Dialog box in Flutter',
      'Flutter – Dialogs',
      'Flutter – Handling videos',
      'Flutter – Expansion Tile Card',
      'Flutter – Tabs',
      'Flutter – Horizontal List',
      'Flutter – Working with Charts',
      'Flutter – Convex Bottombar',
      'Flutter – Slidable',
      'Flutter – Snackbar',
    ],
  ),
  Topic(
    id: 4,
    name: 'Design & Animations',
    image: 'https://via.placeholder.com/150',
    description: 'Implementing design patterns and animations.',
    sections: [
      'Customizing Fonts in Flutter',
      'Flutter – Themes',
      'Flutter – Auto size text',
      'Flutter – Skeleton Text',
      'Flutter – Animation in Route Transition',
      'Flutter – Ripple Effect',
      'Flutter – Lazy Loader',
      'Flutter – Radial Hero Animation',
      'Flutter – Hinge Animation',
      'Flutter – Lottie Animation',
      'ProgressIndicator in Flutter',
      'Flutter – Physics Simulation in Animation',
      'Flutter – Using Google fonts',
      'Flutter – Rotate Transition',
      'Flutter – Animated Splash Screen',
      'Flutter – Shimmer',
      'Rive animations in Flutter',
    ],
  ),
  Topic(
    id: 5,
    name: 'Forms & Gestures',
    image: 'https://via.placeholder.com/150',
    description: 'Handling user input via forms and gestures.',
    sections: [
      'Form Validation in Flutter',
      'Designing a Form Submission Page in Flutter',
      'Flutter – Gestures',
    ],
  ),
  Topic(
    id: 6,
    name: 'Navigation & Routing',
    image: 'https://via.placeholder.com/150',
    description: 'Managing app navigation and routing.',
    sections: [
      'Routes and Navigator in Flutter',
      'Multi-Page Applications in Flutter',
      'Flutter – Named Routes',
      'Flutter – Arguments in Named Routes',
      'Flutter – Return Data from Screen',
      'URLs in Flutter',
      'Retrieve Data From TextFields in Flutter',
      'Flutter – WebSockets',
      'Flutter – Avoiding Jank',
      'Flutter – Updating Data on the Internet',
      'Flutter – Fetching Data From the Internet',
      'Flutter – Deleting Data On The Internet',
      'Flutter – Sending Data To the Internet',
      'Flutter – Send Data to Screen',
      'Flutter – Send Data to the Screen using RouteSettings',
    ],
  ),
  Topic(
    id: 7,
    name: 'Accessing Device',
    image: 'https://via.placeholder.com/150',
    description: 'Using device features like camera, storage, sensors.',
    sections: [
      'Gallery Access in Flutter',
      'Camera Access in Flutter',
      'Background local notifications in Flutter',
      'Restrict Landscape Mode in Flutter',
    ],
  ),
  Topic(
    id: 8,
    name: 'Advanced Concepts',
    image: 'https://via.placeholder.com/150',
    description: 'Exploring advanced Flutter and Dart topics.',
    sections: [
      'Flutter – Read and Write Data on Firebase',
      'Mail and SMS in Flutter',
      'Making Calls in Flutter',
      'FAB – Speed Dial in Flutter',
      'Flutter – Wakelock',
      'Implementing REST API in Flutter',
      'HTTP GET Response in Flutter',
    ],
  ),
  Topic(
    id: 9,
    name: 'App Projects',
    image: 'https://via.placeholder.com/150',
    description: 'Building complete Flutter applications.',
    sections: [
      'Basic Quiz App In Flutter API',
      'A Hello World App Using Flutter',
      'Creating a Simple Application in Flutter',
      'Flutter – Simple PDF-Generating App',
      'Flutter – Dice Roller App',
      'Flutter – Magic 8-Ball App',
    ],
  ),
];
